apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# define base to customize
bases:
  - ../../base

# overwrite configuration
patchesStrategicMerge:
  - configMap.yaml

namePrefix: dev-

commonLabels:
  stage: dev
