apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - configMap.yaml  # overwrite configuration

namePrefix: staging-

commonLabels:
  stage: staging